(async()=>{
 'use strict';const $=id=>document.getElementById(id),A=window.cpAuth;let items=[],offset=0,hasMore=false,busy=false;
 const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const date=v=>v?new Date(v).toLocaleString('ko-KR'):'—';
 function message(text,error=false){$('message').textContent=text;$('message').className='status-message'+(error?' err':'');}
 async function api(path,method='GET',body){const {data:{session}}=await A.client.auth.getSession();if(!session)throw new Error('로그인이 만료되었습니다. 다시 로그인해 주세요.');const r=await fetch('/api/career/'+path,{method,headers:{Authorization:'Bearer '+session.access_token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.error||'요청을 처리하지 못했습니다.');}return path.startsWith('files/')?r.blob():r.json();}
 function render(){const list=$('deliveries');list.replaceChildren();const mode=$('mode').value,selected=items.filter(x=>mode==='all'||x.mode===mode);
  for(const item of selected){const d=node('details');d.className='delivery';const summary=node('summary'),title=node('span');title.className='delivery-summary';title.append(node('strong',item.company),node('span',item.subject));const sub=node('span',date(item.sent_at||item.created_at)+' · '+item.recipient);sub.className='delivery-sub';title.append(sub);const badges=node('span');badges.className='delivery-badges';
   for(const [text,cls] of [[{auto:'자동 발송',review:'검수 후 발송',test:'테스트'}[item.mode],''],[{draft:'발송 준비',sending:'접수 확인 중',sent:'발송 접수',failed:'발송 실패',delivery_unknown:'결과 불명'}[item.status]||item.status,''],[item.first_open_at?'읽음 추정':'확인 안 됨',item.first_open_at?'open':'']]){const b=node('span',text);b.className='delivery-badge '+cls;badges.append(b);}summary.append(title,badges);d.append(summary);const dl=node('dl');for(const [k,v] of [['받는 사람',item.recipient],['발송 접수',date(item.sent_at)],['첫 열람 신호',date(item.first_open_at)]])dl.append(node('dt',k),node('dd',v));d.append(dl);const body=node('div',item.body);body.className='delivery-body';d.append(body);if(item.reason)d.append(node('p',item.reason));
   if(item.document_id){const b=node('button','첨부 지원서 다운로드');b.className='btn';b.type='button';b.onclick=async()=>{b.disabled=true;try{const blob=await api('files/'+item.document_id),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=blob.type==='application/pdf'?'지원서.pdf':'지원서.docx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){message(e.message,true);}finally{b.disabled=false;}};d.append(b);}list.append(d);
  }
  if(!selected.length){const p=node('p',items.length?'선택한 방식의 메일이 없습니다. 이전 메일을 더 불러올 수 있습니다.':'아직 발송한 지원 메일이 없습니다.');p.className='history-empty';list.append(p);} $('more').hidden=!hasMore;
 }
 async function load(reset=true){if(busy)return;busy=true;try{const result=await api('deliveries?offset='+(reset?0:offset));items=reset?result.items:[...items,...result.items];offset=items.length;hasMore=result.has_more;render();}finally{busy=false;}}
 async function mail(){const s=await api('state');$('mail-state').textContent=s.mail?'연결된 계정: '+s.mail.email:'아직 연결한 개인 메일이 없습니다.';$('connect').hidden=!!s.mail;$('disconnect').hidden=!s.mail;}
 function action(id,fn){$(id).onclick=async()=>{$(id).disabled=true;try{await fn();}catch(e){message(e.message,true);}finally{$(id).disabled=false;}};}
 try{const auth=await A.ensure('complete');if(auth.state!=='complete')return;await Promise.all([mail(),load()]);message('발송 이력과 열람 신호를 불러왔습니다.');
  const result=new URLSearchParams(location.search).get('mail');if(result){const messages={connected:'개인 메일을 연결했습니다.',cancelled:'메일 연결을 취소했습니다.',missing_send_permission:'메일 발송 권한을 받지 못했습니다. 다시 연결할 때 이메일 전송 권한을 허용해 주세요.',missing_refresh_token:'연결을 유지할 인증 정보를 받지 못했습니다. Gmail 연결을 다시 시도해 주세요.'};if(messages[result])message(messages[result],result.startsWith('missing_'));history.replaceState(null,'',location.pathname);}
  action('connect',async()=>{const r=await api('mail-connect','POST',{provider:'google'}),u=new URL(r.url);if(u.origin!=='https://accounts.google.com')throw new Error('연결 주소를 확인해 주세요.');location.assign(u.href);});action('disconnect',async()=>{await api('mail','DELETE');await mail();message('메일 연결을 해제했습니다.');});action('refresh',async()=>{await Promise.all([mail(),load()]);message('최신 상태를 불러왔습니다.');});action('more',()=>load(false));$('mode').onchange=render;
  setInterval(()=>{if(!document.hidden&&offset<=25&&!document.querySelector('.delivery[open]'))load().catch(()=>{});},15000);
 }catch(e){message(e.message,true);}
})();
