(async()=>{
'use strict';
const $=id=>document.getElementById(id),A=window.cpAuth;
let state={files:[],rule:null,draft:null},mail=null,ready=false,busy=false,editing=false,dirty=false,draftVersion=0,baseVersion=null,timer=null,draftTask=Promise.resolve(),draftError=null;
const text=(id,value)=>{if($(id))$(id).textContent=value;};
const date=value=>value?new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
function message(value,error=false){text('resume-message',value);$('resume-message').classList.toggle('err',error);text('save-feedback',value);}
function lock(value){busy=value;$('resume-editor').disabled=value||!ready;$('resume-enabled').disabled=value||!ready;$('save-resume-rule').disabled=value||!ready;for(const id of ['start-preparation','edit-preparation','continue-preparation','leave-preparation','cancel-preparation','connect','disconnect','pause-saved','stop-resume'])$(id).disabled=value||!ready;}
async function api(path,method='GET',body){const {data:{session}}=await A.client.auth.getSession();if(!session)throw new Error('다시 로그인해 주세요.');const r=await fetch('/api/career/'+path,{method,headers:{Authorization:'Bearer '+session.access_token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){const b=await r.json().catch(()=>({}));const error=new Error(b.error||'요청을 처리하지 못했습니다.');error.status=r.status;throw error;}return path.startsWith('files/')?r.blob():r.json();}
function notify(){dispatchEvent(new CustomEvent('cpaping:resume-loaded',{detail:state}));}
function entries(dl,values){dl.replaceChildren();for(const [key,value] of values){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;row.append(dt,dd);dl.append(row);}}
function summary(){const r=state.rule,file=state.files.find(f=>f.id===r?.resume_file_id),registered=!!r?.resume_file_id;
 $('preparation-empty').hidden=registered||!!state.draft;$('preparation-summary').hidden=!registered;$('preparation-draft').hidden=!state.draft;
 text('preparation-lead',registered?'등록된 내용을 확인하고, 변경이 필요할 때 수정하세요.':state.draft?'작성 중인 내용을 이어서 완성해 주세요.':'이력서와 지원 조건을 한 번에 준비하세요.');
 const status=r?.enabled?'새 공고 지원 켜짐':'새 공고 지원 꺼짐',mode=r?.mode==='auto'?'자동발송':'수동발송 · 검수 후 보내기';
 text('resume-rule-state',status);text('summary-mode',mode);text('summary-file',file?.name||'등록된 이력서 없음');text('summary-mail',mail?.email||'연결 필요');text('saved-at',r?.updated_at?'마지막 저장 · '+date(r.updated_at):'');
 $('pause-saved').hidden=!r?.enabled;$('stop-resume').hidden=!r?.enabled;
 if(registered)entries($('registered-summary'),[['이력서',file?.name||'파일 확인 필요'],['지원자',r.applicant_name||'—'],['발신 Gmail',mail?.email||'연결 필요'],['답장 자동 확인',!mail?'Gmail 연결 필요':!mail.reply_read_enabled?'읽기 권한 추가 연결 필요':mail.reply_sync_error||('사용 중'+(mail.reply_checked_at?' · 최근 확인 '+date(mail.reply_checked_at):' · 다음 작업에서 확인'))],['지원 대상',(r.filters?.employment||[]).map(x=>x==='Full Time'?'풀타임':'파트타임').join(' · ')+' / 신입·수습'],['발송 방식',mode],['현재 지원 상태',status],['메일 제목',r.mail_subject_template||'—'],['메일 본문',r.mail_body_template||'—'],['마지막 저장',date(r.updated_at)]]);
}
function populate(useDraft=false){const r=state.rule||{},d=useDraft?state.draft?.data:null;
 baseVersion=useDraft&&state.draft?state.draft.base_rule_updated_at:r.updated_at||null;draftVersion=state.draft?.version||0;
 $('resume-file-id').value=d?d.resume_file_id||'':r.resume_file_id||'';
 $('applicant-name').value=d?d.applicant_name||'':r.applicant_name||'';
 $('resume-subject').value=d?d.subject:r.mail_subject_template||'[입사지원] [회계법인] - {이름}';
 $('resume-body').value=d?d.body:r.mail_body_template||'안녕하세요.\n[회계법인] 채용에 지원하는 {이름}입니다.\n이력서를 첨부하오니 검토 부탁드립니다.\n감사합니다.\n{이름} 드림';
 const employment=d?d.employment:r.filters?.employment||['Full Time','Part Time'];$('resume-full').checked=employment.includes('Full Time');$('resume-part').checked=employment.includes('Part Time');
 $('resume-mode').value=d?d.mode:r.mode||'review';$('resume-enabled').checked=(d?d.enabled:r.enabled)===true;$('resume-confirmed').checked=false;$('resume-consent').checked=false;dirty=false;notify();
}
function data(){return {resume_file_id:$('resume-file-id').value||null,applicant_name:$('applicant-name').value,subject:$('resume-subject').value,body:$('resume-body').value,employment:[$('resume-full').checked?'Full Time':null,$('resume-part').checked?'Part Time':null].filter(Boolean),mode:$('resume-mode').value,enabled:$('resume-enabled').checked,step:window.cpResumeSteps?.current||0};}
function saveDraft(){clearTimeout(timer);const snapshot=data();text('draft-save-state','임시 저장 중…');draftTask=draftTask.catch(()=>{}).then(async()=>{if(draftError?.status===409)throw draftError;const saved=await api('resume-draft','PUT',{data:snapshot,version:draftVersion,base_rule_updated_at:baseVersion});state.draft=saved;draftVersion=saved.version;if(JSON.stringify(snapshot)===JSON.stringify(data()))dirty=false;text('draft-save-state','작성 내용 임시 저장됨');return saved;}).catch(e=>{draftError=e;$('retry-resume').hidden=false;text('draft-save-state','임시 저장 실패');message(e.message+' 입력한 내용은 이 화면에 유지됩니다.',true);throw e;});draftTask.catch(()=>{});return draftTask;}
function changed(){if(!editing||busy)return;dirty=true;text('draft-save-state','저장할 변경 내용이 있습니다.');clearTimeout(timer);timer=setTimeout(()=>saveDraft().catch(()=>{}),700);}
function home(){editing=false;clearTimeout(timer);$('resume-form').hidden=true;$('preparation-home').hidden=false;summary();$('preparation-title').tabIndex=-1;$('preparation-title').focus();}
async function load(){state=await api('resume-state');draftVersion=state.draft?.version||0;summary();}
async function begin(resume=false){populate(!!state.draft);$('preparation-home').hidden=true;$('resume-form').hidden=false;editing=true;window.cpResumeSteps?.show(resume?state.draft?.data?.step||0:0);text('cancel-preparation',state.rule?.resume_file_id?'수정 취소':'작성 취소');message('한 단계씩 작성하고 마지막에 저장해 주세요.');await saveDraft();}
async function download(id){if(!id)return;const blob=await api('files/'+id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=state.files.find(f=>f.id===id)?.name||'이력서';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function mailState(){const result=await api('state');mail=result.mail||null;text('mail-state',mail?'연결된 계정: '+mail.email:'연결한 계정이 없습니다.');text('mail-badge',mail?'연결됨':'미연결');$('connect').hidden=!!mail?.reply_read_enabled;text('connect',mail?'답장 확인 권한 연결':'Gmail 연결');$('disconnect').hidden=!mail;text('reply-connection-state',mail?.reply_read_enabled?(mail.reply_sync_error||'지원 관련 답장을 자동으로 확인합니다.'):'답장을 확인하려면 Google 연결 화면에서 메일 읽기 권한을 허용해 주세요.');dispatchEvent(new CustomEvent('cpaping:mail-loaded',{detail:mail}));summary();}
function action(id,fn){$(id).onclick=async()=>{if(busy||!ready)return;lock(true);try{await fn();}catch(e){message(e.message,true);}finally{lock(false);}};}
async function initialise(){lock(true);try{await load();let mailFailed=false;try{await mailState();}catch{mailFailed=true;text('reply-connection-state','Gmail 연결 상태를 확인하지 못했습니다. 새로고침해 주세요.');}ready=true;draftError=null;draftTask=Promise.resolve();populate();home();$('retry-resume').hidden= !mailFailed;message(state.rule?.resume_file_id?'현재 등록된 내용을 확인하세요.':'지원준비를 시작하거나 작성 중인 내용을 이어서 완성하세요.');const result=new URLSearchParams(location.search).get('mail');if(result){history.replaceState(null,'',location.pathname);if(state.draft)await begin(true);message(result==='connected'?'Gmail 연결과 답장 확인 권한을 확인했습니다.':result==='connected_send_only'?'발송 연결은 완료했습니다. 답장 자동 확인을 사용하려면 읽기 권한도 연결해 주세요.':'Gmail 연결을 완료하지 못했습니다. 다시 연결해 주세요.',!['connected','connected_send_only'].includes(result));}}catch(e){message(e.message,true);$('retry-resume').hidden=false;}finally{lock(false);}}
try{const auth=await A.ensure('needs_profile');if(!['complete','needs_profile'].includes(auth.state))return;
 action('start-preparation',()=>begin());action('edit-preparation',()=>begin());action('continue-preparation',()=>begin(true));
 action('leave-preparation',async()=>{await saveDraft();home();message('작성 중인 내용을 저장했습니다. 다음에 이어서 작성할 수 있습니다.');});
 action('cancel-preparation',async()=>{clearTimeout(timer);await draftTask.catch(()=>{});if(draftVersion)await api('resume-draft','DELETE',{version:draftVersion});state.draft=null;dirty=false;draftVersion=0;window.cpResumeFile=null;draftError=null;draftTask=Promise.resolve();$('resume-upload').value='';await load();populate();home();message('작성을 취소했습니다. 기존에 저장한 설정은 유지됩니다.');});
 action('connect',async()=>{if(editing)await saveDraft();const r=await api('mail-connect','POST',{provider:'google'}),u=new URL(r.url);if(u.origin!=='https://accounts.google.com')throw new Error('연결 주소를 확인해 주세요.');location.assign(u.href);});
 action('disconnect',async()=>{await api('mail','DELETE');await load();baseVersion=state.rule?.updated_at||null;$('resume-enabled').checked=false;await mailState();message('Gmail 연결을 해제하고 새 공고 지원을 중지했습니다.');});
 action('refresh-mail',mailState);action('download-current',()=>download($('resume-file-id').value));action('download-saved',()=>download(state.rule?.resume_file_id));
 const pause=async()=>{await api('resume-stop','POST',{});await load();baseVersion=state.rule?.updated_at||null;$('resume-enabled').checked=false;notify();summary();message('새 공고 지원을 중지했습니다.');};action('pause-saved',pause);action('stop-resume',pause);
 $('resume-form').addEventListener('input',changed);addEventListener('cpaping:step-changed',changed);
 $('upload-resume').onclick=async()=>{if(busy||!ready)return;lock(true);const b=$('upload-resume');b.disabled=true;b.textContent='업로드 중…';try{const f=window.cpResumeFile||$('resume-upload').files[0];if(!f||f.size>3000000||!/\.(pdf|docx)$/i.test(f.name))throw new Error('3MB 이하 PDF 또는 Word(.docx)를 선택해 주세요.');const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('파일을 읽지 못했습니다.'));reader.readAsDataURL(f);});const saved=await api('resumes','POST',{name:f.name,data_base64:encoded});state.files.push({id:saved.id,name:f.name,created_at:new Date().toISOString()});$('resume-file-id').value=saved.id;$('resume-confirmed').checked=false;$('resume-consent').checked=false;dirty=true;window.cpResumeFile=null;$('resume-upload').value='';notify();dispatchEvent(new Event('cpaping:resume-uploaded'));await saveDraft();message('이력서를 업로드했습니다. 최종 저장하면 새 파일이 적용됩니다.');}catch(e){message(e.message,true);}finally{lock(false);b.disabled=!window.cpResumeFile;b.textContent='파일 업로드';}};
 $('resume-form').onsubmit=async e=>{e.preventDefault();if(busy||!ready||!editing||window.cpResumeSteps?.prepareSubmit()===false)return;const d=data();if(!d.resume_file_id||!d.applicant_name||!d.employment.length||!$('resume-confirmed').checked){message('이력서·이름·지원 조건과 파일 확인 항목을 확인해 주세요.',true);return;}if(d.mode==='auto'&&d.enabled&&!$('resume-consent').checked){message('자동 발송 동의를 확인해 주세요.',true);return;}lock(true);let committed=false;try{await saveDraft();await api('resume-rule','PUT',{...d,filters:{employment:d.employment},updated_at:baseVersion,draft_version:draftVersion,file_confirmed:true,auto_consent:$('resume-consent').checked});committed=true;dirty=false;await load();populate();home();message('지원준비를 저장했습니다. 등록된 내용을 확인하세요.');}catch(e){message(committed?'저장은 완료했습니다. 다시 불러오기로 저장된 내용을 확인해 주세요.':e.message,true);if(committed){ready=false;$('retry-resume').hidden=false;}}finally{lock(false);}};
 $('retry-resume').onclick=initialise;addEventListener('beforeunload',e=>{if(editing&&dirty){e.preventDefault();e.returnValue='';}});
 await initialise();
}catch(e){message(e.message,true);}
})();
