(async()=>{
'use strict';
const $=id=>document.getElementById(id),A=window.cpAuth,T=window.cpResumeTemplate;
let state={files:[],rule:null,draft:null},mail=null,ready=false,busy=false,editing=false,dirty=false,draftVersion=0,baseVersion=null,timer=null,draftTask=Promise.resolve(),draftError=null;
const text=(id,value)=>{if($(id))$(id).textContent=value;};
const date=value=>value?new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
function message(value,error=false){text('resume-message',value);$('resume-message').hidden=!value;$('resume-message').classList.toggle('err',error);}
function lock(value){busy=value;for(const id of ['resume-editor','save-resume-rule','start-preparation','edit-preparation','continue-preparation','leave-preparation','cancel-preparation','connect','disconnect','refresh-mail','retry-upload','keep-resume','automation-enabled','automation-consent','confirm-automation','cancel-automation'])$(id).disabled=value||!ready;for(const radio of document.querySelectorAll('[name=automation-mode]'))radio.disabled=value||!ready;$('automation-panel').setAttribute('aria-busy',String(value));}

async function api(path,method='GET',body){const {data:{session}}=await A.client.auth.getSession();if(!session)throw new Error('다시 로그인해 주세요.');const r=await fetch('/api/career/'+path,{method,headers:{Authorization:'Bearer '+session.access_token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){const b=await r.json().catch(()=>({}));const error=new Error(b.error||'요청을 처리하지 못했습니다.');error.status=r.status;throw error;}return path.startsWith('files/')?r.blob():r.json();}
function notify(){dispatchEvent(new CustomEvent('cpaping:resume-loaded',{detail:state}));}
function entries(dl,values){dl.replaceChildren();for(const [key,value] of values){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;row.append(dt,dd);dl.append(row);}}
function summary(){const r=state.rule,file=state.files.find(f=>f.id===r?.resume_file_id),registered=!!r?.resume_file_id;
 $('preparation-empty').hidden=registered||!!state.draft;$('preparation-summary').hidden=!registered;$('preparation-draft').hidden=!state.draft;
 text('preparation-lead',registered?'':state.draft?'작성 중인 내용을 이어서 완성해 주세요.':'이력서와 지원 조건을 한 번에 준비하세요.');
 const status=r?.enabled?'자동 지원 켜짐':'자동 지원 꺼짐',mode=r?.mode==='auto'?'바로 발송':'검수 후 발송';
 $('download-word').hidden=!r?.resume_docx_file_id;
 automationSummary();
 if(registered)entries($('registered-summary'),[['PDF',file?.name||'파일 확인 필요'],['Word',state.files.find(f=>f.id===r?.resume_docx_file_id)?.name||'추가 등록 필요'],['지원자',r.applicant_name||'—'],['발신 Gmail',mail?.email||'연결 필요'],['지원 대상',(r.filters?.employment||[]).map(x=>x==='Full Time'?'풀타임':'파트타임').join(' · ')+' / 신입·수습'],['발송 방식',mode],['현재 지원 상태',status],['메일 제목',T.example(r.mail_subject_template,r.applicant_name)||'—'],['메일 본문',T.example(r.mail_body_template,r.applicant_name)||'—'],['마지막 저장',date(r.updated_at)]]);
}
let pendingAutomation=null;
function automationSummary(){const r=state.rule;$('automation-panel').hidden=!r?.resume_file_id;$('automation-enabled').checked=!!r?.enabled;text('automation-label',r?.enabled?'켜짐':'꺼짐');text('automation-status',r?.enabled?(r.mode==='auto'?'조건에 맞는 새 공고에 바로 발송합니다.':'새 공고의 지원 내용을 준비하고, 검수를 기다립니다.'):'자동 지원이 꺼져 있습니다. 언제든 다시 켤 수 있어요.');$('automation-options').hidden=!r?.enabled;$('automation-consent-panel').hidden=true;$('automation-consent').checked=false;for(const input of document.querySelectorAll('[name=automation-mode]'))input.checked=input.value===(r?.mode||'review');}
function showAutomationConsent(){text('automation-label',state.rule.enabled?'켜짐':'적용 전');$('automation-options').hidden=false;$('automation-consent-panel').hidden=false;$('automation-consent').checked=false;for(const input of document.querySelectorAll('[name=automation-mode]'))input.checked=input.value==='auto';text('automation-status','동의 후 적용하면 바로 발송으로 변경됩니다.');$('automation-consent').focus();}
async function setAutomation(enabled,mode,consent=false){if(busy||!ready)return;lock(true);message('변경 사항을 저장하는 중…');try{const result=await api('resume-automation','PUT',{enabled,mode,auto_consent:consent,updated_at:state.rule.updated_at});state.rule=result.rule;state.draft=result.draft;pendingAutomation=null;draftVersion=state.draft?.version||0;summary();message(enabled?(mode==='auto'?'자동 지원을 켰습니다. 조건에 맞는 새 공고에 바로 발송합니다.':'자동 지원을 켰습니다. 지원 내용을 검수한 후 발송할 수 있습니다.'):'자동 지원을 껐습니다. 아직 발송하지 않은 대기 건도 멈췄습니다.');}catch(e){pendingAutomation=null;try{await load();}catch{}summary();message(e.message+' 저장된 상태를 다시 확인해 주세요.',true);$('retry-resume').hidden=false;}finally{lock(false);}}
function populate(useDraft=false){const r=state.rule||{},d=useDraft?state.draft?.data:null;
 baseVersion=useDraft&&state.draft?state.draft.base_rule_updated_at:r.updated_at||null;draftVersion=state.draft?.version||0;
 $('resume-docx-file-id').value=d?d.resume_docx_file_id||'':r.resume_docx_file_id||'';
 $('resume-file-id').value=d?d.resume_file_id||'':r.resume_file_id||'';
 $('applicant-name').value=d?d.applicant_name||'':r.applicant_name||'';
 $('resume-subject').value=T.normalize(d?d.subject:r.mail_subject_template||'[입사지원] [회계법인] - [이름]');
 $('resume-body').value=T.normalize(d?d.body:r.mail_body_template||'안녕하세요.\n[회계법인] 채용에 지원하는 [이름]입니다.\n이력서를 첨부하오니 검토 부탁드립니다.\n감사합니다.\n[이름] 드림');
 const employment=d?d.employment:r.filters?.employment||['Full Time','Part Time'];$('resume-full').checked=employment.includes('Full Time');$('resume-part').checked=employment.includes('Part Time');
 $('resume-mode').value=d?d.mode:r.mode||'review';window.cpResumeWillEnable=r.resume_file_id?r.enabled===true:true;text('save-resume-rule',r.resume_file_id?'변경 내용 저장 →':'저장하고 지원 시작 →');text('review-save-help',r.resume_file_id?(r.enabled?'저장하면 변경한 내용으로 자동 지원을 계속합니다.':'변경 내용만 저장합니다. 자동 지원은 꺼진 상태로 유지됩니다.'):'저장하면 선택한 방식으로 자동 지원을 시작합니다.');window.cpResumeFile=null;window.cpResumeUploadState='idle';$('resume-chosen').dataset.error='false';$('retry-upload').hidden=true;$('keep-resume').hidden=true;$('resume-confirmed').checked=false;$('resume-consent').checked=false;dirty=false;notify();
}
function data(){return {resume_docx_file_id:$('resume-docx-file-id').value||null,resume_file_id:$('resume-file-id').value||null,applicant_name:$('applicant-name').value,subject:$('resume-subject').value,body:$('resume-body').value,employment:[$('resume-full').checked?'Full Time':null,$('resume-part').checked?'Part Time':null].filter(Boolean),mode:$('resume-mode').value,enabled:window.cpResumeWillEnable,flow_version:2,step:window.cpResumeSteps?.current||0};}
function saveDraft(){clearTimeout(timer);const snapshot=data();text('draft-save-state','임시 저장 중…');draftTask=draftTask.catch(()=>{}).then(async()=>{if(draftError?.status===409)throw draftError;const saved=await api('resume-draft','PUT',{data:snapshot,version:draftVersion,base_rule_updated_at:baseVersion});state.draft=saved;draftVersion=saved.version;if(JSON.stringify(snapshot)===JSON.stringify(data()))dirty=false;text('draft-save-state','작성 내용 임시 저장됨');return saved;}).catch(e=>{draftError=e;$('retry-resume').hidden=false;text('draft-save-state','임시 저장 실패');message(e.message+' 입력한 내용은 이 화면에 유지됩니다.',true);throw e;});draftTask.catch(()=>{});return draftTask;}
function changed(){if(!editing||busy)return;dirty=true;text('draft-save-state','저장할 변경 내용이 있습니다.');clearTimeout(timer);timer=setTimeout(()=>saveDraft().catch(()=>{}),700);}
function home(){editing=false;clearTimeout(timer);$('resume-form').hidden=true;$('preparation-home').hidden=false;summary();$('preparation-title').tabIndex=-1;$('preparation-title').focus();}
async function load(){state=await api('resume-state');draftVersion=state.draft?.version||0;summary();}
async function begin(resume=false){populate(!!state.draft);$('preparation-home').hidden=true;$('resume-form').hidden=false;editing=true;window.cpResumeSteps?.show(resume&&state.draft?.data?.flow_version===2?state.draft.data.step||0:0);text('cancel-preparation',state.rule?.resume_file_id?'수정 취소':'작성 취소');message('한 단계씩 작성하고 마지막에 저장해 주세요.');await saveDraft();}
async function download(id){if(!id)return;const blob=await api('files/'+id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=state.files.find(f=>f.id===id)?.name||'이력서';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function mailState(){const result=await api('state');mail=result.mail||null;window.cpResumeMail=mail;text('mail-state',mail?'연결된 계정: '+mail.email:'연결한 계정이 없습니다.');text('mail-badge',mail?'연결됨':'미연결');$('connect').hidden=!!mail;text('connect','Gmail 연결');$('disconnect').hidden=!mail;text('reply-connection-state','합격·불합격 결과는 지원현황에서 직접 기록할 수 있습니다.');dispatchEvent(new CustomEvent('cpaping:mail-loaded',{detail:mail}));summary();}
function action(id,fn){$(id).onclick=async()=>{if(busy||!ready)return;lock(true);try{await fn();}catch(e){message(e.message,true);}finally{lock(false);}};}
async function initialise(){lock(true);try{await load();let mailFailed=false;try{await mailState();}catch{mailFailed=true;text('reply-connection-state','Gmail 연결 상태를 확인하지 못했습니다. 새로고침해 주세요.');}ready=true;draftError=null;draftTask=Promise.resolve();populate();home();$('retry-resume').hidden= !mailFailed;message('');const result=new URLSearchParams(location.search).get('mail');if(result){history.replaceState(null,'',location.pathname);if(state.draft)await begin(true);message(['connected','connected_send_only'].includes(result)?'Gmail 연결을 완료했습니다.':'Gmail 연결을 완료하지 못했습니다. 다시 연결해 주세요.',!['connected','connected_send_only'].includes(result));}}catch(e){message(e.message,true);$('retry-resume').hidden=false;}finally{lock(false);}}
try{const auth=await A.ensure('needs_profile');if(!['complete','needs_profile'].includes(auth.state))return;
 action('start-preparation',()=>begin());action('edit-preparation',()=>begin());action('continue-preparation',()=>begin(true));
 action('leave-preparation',async()=>{await saveDraft();home();message('작성 중인 내용을 저장했습니다. 다음에 이어서 작성할 수 있습니다.');});
 action('cancel-preparation',async()=>{clearTimeout(timer);await draftTask.catch(()=>{});if(draftVersion)await api('resume-draft','DELETE',{version:draftVersion});state.draft=null;dirty=false;draftVersion=0;window.cpResumeFile=null;draftError=null;draftTask=Promise.resolve();$('resume-upload').value='';await load();populate();home();message('작성을 취소했습니다. 기존에 저장한 설정은 유지됩니다.');});
 action('connect',async()=>{if(editing)await saveDraft();const r=await api('mail-connect','POST',{provider:'google'}),u=new URL(r.url);if(u.origin!=='https://accounts.google.com')throw new Error('연결 주소를 확인해 주세요.');location.assign(u.href);});
 action('disconnect',async()=>{await api('mail','DELETE');await load();baseVersion=state.rule?.updated_at||null;window.cpResumeWillEnable=state.rule?.resume_file_id?false:true;await mailState();message('Gmail 연결을 해제하고 자동 지원을 껐습니다.');});
 action('refresh-mail',mailState);action('download-saved',()=>download(state.rule?.resume_file_id));action('download-word',()=>download(state.rule?.resume_docx_file_id));
 $('automation-enabled').onchange=async()=>{const enabled=$('automation-enabled').checked;if(enabled&&state.rule.mode==='auto'&&state.rule.consent_version!=='resume-auto-v1'){pendingAutomation={enabled,mode:'auto'};showAutomationConsent();return;}await setAutomation(enabled,state.rule.mode);};
 for(const radio of document.querySelectorAll('[name=automation-mode]'))radio.onchange=async()=>{if(radio.value===state.rule.mode){pendingAutomation=null;automationSummary();return;}if(radio.value==='auto'){pendingAutomation={enabled:true,mode:'auto'};showAutomationConsent();}else await setAutomation(true,'review');};
 $('confirm-automation').onclick=async()=>{if(!$('automation-consent').checked){message('바로 발송 동의를 확인해 주세요.',true);$('automation-consent').focus();return;}if(pendingAutomation)await setAutomation(pendingAutomation.enabled,pendingAutomation.mode,true);};
 $('cancel-automation').onclick=()=>{pendingAutomation=null;automationSummary();message('');};
 $('resume-form').addEventListener('input',changed);addEventListener('cpaping:step-changed',changed);
 async function upload(){if(busy||!ready||!editing)return;lock(true);window.cpResumeUploadState='uploading';$('resume-drop').setAttribute('aria-busy','true');$('retry-upload').hidden=true;$('keep-resume').hidden=true;$('resume-chosen').dataset.error='false';text('resume-chosen',(window.cpResumeFile?.name||'파일')+' · 업로드 중…');message('');try{const f=window.cpResumeFile;if(!f||f.size>3000000||!/\.(pdf|docx)$/i.test(f.name))throw new Error('3MB 이하 PDF 또는 Word(.docx)를 선택해 주세요.');const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('파일을 읽지 못했습니다.'));reader.readAsDataURL(f);});const saved=await api('resumes','POST',{name:f.name,data_base64:encoded});state.files.push({id:saved.id,name:f.name,created_at:new Date().toISOString()});$(/\.docx$/i.test(f.name)?'resume-docx-file-id':'resume-file-id').value=saved.id;$('resume-confirmed').checked=false;$('resume-consent').checked=false;dirty=true;window.cpResumeFile=null;window.cpResumeUploadState='done';$('resume-upload').value='';notify();dispatchEvent(new Event('cpaping:resume-uploaded'));await saveDraft();}catch(e){if(window.cpResumeFile){window.cpResumeUploadState='error';text('resume-chosen','업로드하지 못했습니다. 다시 시도하거나 다른 파일을 선택해 주세요.');$('resume-chosen').dataset.error='true';$('retry-upload').hidden=false;$('keep-resume').hidden=!$('resume-file-id').value;}message(e.message,true);}finally{lock(false);$('resume-drop').setAttribute('aria-busy','false');}}
 addEventListener('cpaping:resume-picked',upload);$('retry-upload').onclick=upload;
 $('keep-resume').onclick=()=>{if(busy)return;window.cpResumeFile=null;window.cpResumeUploadState='idle';$('resume-upload').value='';$('resume-chosen').dataset.error='false';$('retry-upload').hidden=true;$('keep-resume').hidden=true;notify();message('기존 파일을 유지합니다.');};
 $('resume-form').onsubmit=async e=>{e.preventDefault();if(busy||!ready||!editing||window.cpResumeSteps?.prepareSubmit()===false)return;const d=data();if(!d.resume_file_id||!d.resume_docx_file_id||!d.applicant_name||!d.employment.length||!$('resume-confirmed').checked){message('이력서·이름·지원 조건과 파일 확인 항목을 확인해 주세요.',true);return;}if(d.mode==='auto'&&d.enabled&&!$('resume-consent').checked){message('자동 발송 동의를 확인해 주세요.',true);return;}lock(true);let committed=false;try{await saveDraft();await api('resume-rule','PUT',{...d,filters:{employment:d.employment},updated_at:baseVersion,draft_version:draftVersion,file_confirmed:true,auto_consent:$('resume-consent').checked});committed=true;dirty=false;await load();populate();home();message(d.enabled?'저장했습니다. 선택한 방식으로 자동 지원 중입니다.':'변경 내용을 저장했습니다. 자동 지원은 꺼져 있습니다.');}catch(e){message(committed?'저장은 완료했습니다. 다시 불러오기로 저장된 내용을 확인해 주세요.':e.message,true);if(committed){ready=false;$('retry-resume').hidden=false;}}finally{lock(false);}};
 $('retry-resume').onclick=initialise;addEventListener('beforeunload',e=>{if(editing&&dirty){e.preventDefault();e.returnValue='';}});
 await initialise();
}catch(e){message(e.message,true);}
})();
